services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: 
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend
      - /backend/node_modules
    ports:
      - "3000:3000" #NestJSのデフォルト
      - "5555:5555" #Prismaのデフォルト
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    ports:
      - "3001:3001" #backendとの競合を避ける
    environment:
      - PORT=3001
    depends_on:
      - backend

volumes:
  postgres_data: