services:
  db:
    container_name: db
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER={POSTGRES_USER}
      - POSTGRES_PASSWORD={POSTGRES_PASSWORD}
      - POSTGRES_DB={POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    container_name: backend
    build: 
      context: ./backend/app
      dockerfile: ../Dockerfile
    volumes:
      - ./backend/app:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
  
  frontend:
    container_name: frontend
    build: 
      context: ./frontend/app
      dockerfile: ../Dockerfile
    volumes:
      - ./frontend/app:/app
    ports:
      - "5173:5173" #Viteを使用
    depends_on:
      - backend