FROM node:20-alpine

WORKDIR /backend

COPY package*.json ./
RUN npm install

COPY . .
RUN npx prisma generate

COPY prisma ./prisma
RUN npx prisma generate

EXPOSE 3000

CMD [ "npm", "run", "start" ]